sources:
  - Tests
templates:
  - .sourcery
args:
  testImports:
    - "@testable import AutobahnDescriptionTests"
    - "@testable import AutobahnFrameworkTests"
    - "@testable import ActionsTests"
